---@meta

---@enum ClipFlags

ClipFlags = {
    kClipTeamBlue               = 1 << 0,
    kClipTeamRed                = 1 << 1,
    kClipTeamYellow             = 1 << 2,
    kClipTeamGreen              = 1 << 3,
    kClipAllPlayers             = 1 << 4,
    kClipAllGrenades            = 1 << 5,
    kClipAllProjectiles         = 1 << 6,
    kClipAllBullets             = 1 << 7,
    kClipAllBuildables          = 1 << 8,
    kClipAllBuildableWeapons    = 1 << 9,
    kClipAllBackpacks           = 1 << 10,
    kClipAllInfoScripts         = 1 << 11,
    kClipInfoScripts            = 1 << 11,
    kClipAllSpawnTurrets        = 1 << 12,
    kClipAllNonPlayers          = 1 << 13,
    kClipPlayers                = 1 << 14,
    kClipPlayersByTeam          = 1 << 14,
    kClipGrenades               = 1 << 15,
    kClipGrenadesByTeam         = 1 << 15,
    kClipProjectiles            = 1 << 16,
    kClipProjectilesByTeam      = 1 << 16,
    kClipBullets                = 1 << 17,
    kClipBulletsByTeam          = 1 << 17,
    kClipBuildables             = 1 << 18,
    kClipBuildablesByTeam       = 1 << 18,
    kClipBuildableWeapons       = 1 << 19,
    kClipBuildableWeaponsByTeam = 1 << 19,
    kClipBackpacks              = 1 << 20,
    kClipBackpacksByTeam        = 1 << 20,
    kClipSpawnTurrets           = 1 << 22,
    kClipSpawnTurretsByTeam     = 1 << 22,
    kClipNonPlayers             = 1 << 23,
    kClipNonPlayersByTeam       = 1 << 23,
}
